<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Lets Go</name>
   <tag></tag>
   <elementGuidId>4f2f4126-9c10-450e-b5fa-3af7ae78bc5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#confirm-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='confirm-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c7c42e19-ead7-498d-b77a-58107080c10b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>confirm-button</value>
      <webElementGuid>ab28edad-675a-40cf-9f4a-8282350e18a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button start-trial__confirm-button</value>
      <webElementGuid>f7da52fd-5be3-473a-abc5-187a5af12e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Let's Go</value>
      <webElementGuid>57c3c13c-5253-4d0c-810f-57c4f9a1b25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;confirm-button&quot;)</value>
      <webElementGuid>c2f19940-dbd9-446d-b091-ab9c6a809da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='confirm-button']</value>
      <webElementGuid>80699aad-2e11-4775-8cc6-8ec67eadf55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='my-app']/div/div/div/div[3]/a</value>
      <webElementGuid>3df037e4-04d6-4d4c-81d9-e2a0672957f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company'])[1]/following::a[1]</value>
      <webElementGuid>644027d1-ff87-4fe8-8a0a-47f1b34d4984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This field is required'])[1]/following::a[1]</value>
      <webElementGuid>5273b4f5-7abf-4b50-bae4-726552bab8b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Agreement'])[1]/preceding::a[1]</value>
      <webElementGuid>4aee9347-a408-427a-874e-8fc02809ceea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Processing Agreement'])[1]/preceding::a[2]</value>
      <webElementGuid>5d9f69a5-179c-4395-820c-b67c78ef19e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a</value>
      <webElementGuid>0dc997c7-65df-4393-900e-b77fe58a2034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'confirm-button' and (text() = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s Go&quot;) or . = concat(&quot;Let&quot; , &quot;'&quot; , &quot;s Go&quot;))]</value>
      <webElementGuid>b26db6e8-090c-4ea5-a2cd-d9c49d052011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::a[1]</value>
      <webElementGuid>44285635-98af-4ec7-8cd0-de8bf96338a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
