<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get started</name>
   <tag></tag>
   <elementGuidId>28c9c465-71f3-4f32-ae5f-10613c36a4ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.home-page__button.home-page__button--start-trial.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-page-banner']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>da5ccf53-b815-459b-a6e7-3ccdd8abd4a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/free-online-trial</value>
      <webElementGuid>82a797af-388d-4d42-9284-79aed687dce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-page__button home-page__button--start-trial button</value>
      <webElementGuid>367937fe-8abf-4e9c-96e1-d9ad5119a599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>b53090d1-3635-49ea-a377-44a255f875e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-page-banner&quot;)/div[@class=&quot;home-page__banner-wrapper&quot;]/a[@class=&quot;home-page__button home-page__button--start-trial button&quot;]</value>
      <webElementGuid>8fcb452a-c5b8-46f6-aa50-587f1cfe1fa1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-page-banner']/div/a</value>
      <webElementGuid>67f5016f-2ed4-47c9-93e4-c5b93b4bdeb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get started')]</value>
      <webElementGuid>d607b9d0-72ab-4e66-aa2e-125396d2fda7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost performance, track work progress and don’t leave any billable second untracked'])[1]/following::a[1]</value>
      <webElementGuid>1e806def-71f3-40e8-8497-f028110649bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Tracking Software'])[1]/following::a[1]</value>
      <webElementGuid>7837b590-57ab-4ffc-88b0-ba3f29127406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time tracking is a necessity, not an option'])[1]/preceding::a[1]</value>
      <webElementGuid>6eef4650-47df-407c-beed-9ac00d70bd05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>6432540f-89d4-435c-9715-7d9e0e4a9d8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/free-online-trial')])[3]</value>
      <webElementGuid>30b76ac1-57a3-454f-8841-3e640b4df896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>309331ba-20be-45d8-8e12-64d499a7231d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/free-online-trial' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>6e7cc906-1931-4571-9da1-c8d878f3783c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
