<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Get started</name>
   <tag></tag>
   <elementGuidId>9edefa33-95e4-4aa6-be7d-150de7ea28be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.home-page__button.home-page__button--start-trial.button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='home-page-banner']/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cd17f114-3906-431f-8af6-bdeaacd53772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/free-online-trial</value>
      <webElementGuid>3638bdbe-fcd6-4269-b205-806fe26a5e38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>home-page__button home-page__button--start-trial button</value>
      <webElementGuid>fe023e2f-f6ec-404e-88e2-ad5cb71a1513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get started</value>
      <webElementGuid>a06c1e09-1991-44ef-b29c-12aadb232dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;home-page-banner&quot;)/div[@class=&quot;home-page__banner-wrapper&quot;]/a[@class=&quot;home-page__button home-page__button--start-trial button&quot;]</value>
      <webElementGuid>33db785b-6abf-46ac-a7f4-99471f4d24ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='home-page-banner']/div/a</value>
      <webElementGuid>77c500d2-1fad-46be-bd82-573c43c25a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Get started')]</value>
      <webElementGuid>6bbee463-dd1f-4efe-9245-0353a7758c53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Boost performance, track work progress and don’t leave any billable second untracked'])[1]/following::a[1]</value>
      <webElementGuid>f10aead7-3f83-41d7-be37-4d98b53e02d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Tracking Software'])[1]/following::a[1]</value>
      <webElementGuid>e5846bc4-d4fd-4be2-966e-946e84d166d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time tracking is a necessity, not an option'])[1]/preceding::a[1]</value>
      <webElementGuid>de784fe2-7ca1-4fd4-8f77-7ce8c13c2ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Get started']/parent::*</value>
      <webElementGuid>9adbb498-3119-43cc-a80a-6e074d55ad52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/free-online-trial')])[3]</value>
      <webElementGuid>96e22ff9-1d5d-4580-877f-36506c117de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/a</value>
      <webElementGuid>74580fc1-1934-40b8-a851-a7b774e0e0cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/free-online-trial' and (text() = 'Get started' or . = 'Get started')]</value>
      <webElementGuid>1512ba9b-2b7a-4800-8d77-ea7d24553ccf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
